# Generated by Django 3.0.4 on 2020-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, to='projects.Task'),
        ),
    ]
